development:
  adapter: mysql2
  database: scoreopenface_development
  encoding: utf8
  username: root
  password: 
		
production:
  adapter: mysql2
  database: scoreopenface_production
  encoding: utf8
  username: root
  password: 